# Generated by Django 4.2.15 on 2024-09-15 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_letter', models.ImageField(upload_to='')),
                ('national_id_card', models.ImageField(upload_to='')),
                ('indigen_letter', models.ImageField(upload_to='')),
                ('primary_certificate', models.ImageField(upload_to='')),
                ('ssce_certificate', models.ImageField(upload_to='')),
                ('reciept', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('bvn', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='BVN must be exactly 11 digits.')])),
                ('nin', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='NIN must be exactly 10 digits.')])),
                ('contact_address', models.TextField()),
                ('local_government_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Account number must be exactly 10 digits.')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='academicinformation',
            constraint=models.UniqueConstraint(fields=('institution', 'id_number'), name='unique_id_number_per_institution'),
        ),
    ]
